### ISSUE TITLE
(node:5690) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.

### ISSUE THREAD

**Issue by leopessanha74** [Kitware/arctic-viewer#26]
After installing and serving a directory I get this warning message:

(node:5690) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.

Ubuntu GNOME 64 bits
node v8.4.0
npm 5.3.0
ArcticViewer 1.5.20

Should I worry about this warning?

The ArcticViewer won't open my data and I can't find out why... 

LightViz@1.0.0 in the other hand opens the same data with no problem.

**Comment by leopessanha74** [comment]
If I don't have to worry with the warning, just close the issue because I don't know if I should have opened in the first place or go to the paraview mailing list =) 

Maybe the data not opening in Arctic has something to do with me not setting info.json correctly.

**Comment by jourdain** [comment]
I don't think you should worry about that warning.

Regarding the data you are trying to load with ArcticViewer can't be the same data as LightViz or Visualizer.

The reason is that ArcticViewer can only browse data that has been somewhat pre-process unlike what you load with ParaView/Visualizer/LightViz.

**Comment by jourdain** [comment]
What is your dataset and `index.json` looks like?

**Comment by leopessanha74** [comment]
I was not aware of that. I was trying to define a regular vtk in a info.json.

How/Where can I pre-process my data in order to use it with ArcticViewer? or is it all a by-hand process using the "[Formats](https://kitware.github.io/arctic-viewer/docs/formats/ImageBasedFormat.html)"  section of the git.io ?

**Comment by jourdain** [comment]
The documentation is pretty weak on that subject but examples can be found here: https://github.com/Kitware/arctic-viewer/tree/master/scripts/examples
