### ISSUE TITLE
cp: cannot stat './node_modules/plotly.js/dist/plotly.min.js': No such file or directory

### ISSUE THREAD

**Issue by defineconst** [Kitware/arctic-viewer#29]
hadoop@ubuntu:~$ /usr/local/bin/LightViz --data /home/hadoop/Downloads/ParaViewData-v4.4.0 --port 8080 --paraview /home/hadoop/Downloads/ParaView-5.4.1-Qt5-OpenGL2-MPI-Linux-64bit --force-offscreen-rendering

  error: unknown option `--force-offscreen-rendering'

hadoop@ubuntu:~$ 

root@ubuntu:/home/hadoop# npm install -g arctic-viewer
/usr/local/bin/ArcticViewer -> /usr/local/lib/node_modules/arctic-viewer/bin/arctic-viewer-cli.js
/usr/local/bin/ArcticViewer2Cinema -> /usr/local/lib/node_modules/arctic-viewer/bin/query-data-model-2-cinema-cli.js
/usr/local/bin/Cinema2ArcticViewer -> /usr/local/lib/node_modules/arctic-viewer/bin/cinema-2-query-data-model-cli.js

> arctic-viewer@1.7.0 postinstall /usr/local/lib/node_modules/arctic-viewer
> cp ./node_modules/plotly.js/dist/plotly.min.js ./dist

cp: cannot stat './node_modules/plotly.js/dist/plotly.min.js': No such file or directory
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! arctic-viewer@1.7.0 postinstall: `cp ./node_modules/plotly.js/dist/plotly.min.js ./dist`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the arctic-viewer@1.7.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-07T07_25_20_635Z-debug.log
root@ubuntu:/home/hadoop#

**Comment by jourdain** [comment]
Good catch thanks for reporting the issue for global install!

I'll fix it later today with a 1.7.1 version...

**Comment by jourdain** [comment]
Fixed in 1.7.1
