### ISSUE TITLE
Sample data server is down

### ISSUE THREAD

**Issue by dangars** [Kitware/arctic-viewer#36]
Hi, I think that the sample data server is down. I tried to download the date with `$ ArcticViewer --download-sample-data` and I got the following error
```
oups something wrong happened while downloading http://tonic.kitware.com/arctic-viewer/diskout-composite.tgz
```

**Comment by jourdain** [comment]
Yes, you are right. As a work around, you can manually download and untgz the files which can be found [here](https://drive.google.com/drive/folders/1Rc_kVCq_UmKMPlD2OR8qQFuyqv_MOSuM?usp=sharing).

**Comment by dangars** [comment]
Thanks a lot!
